version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always



  backend:
    image: fetbubun/kittygram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    restart: always

  frontend:
    image: fetbubun/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/

  gateway:
    image: fetbubun/kittygram_gateway:latest
    env_file: .env
    ports:
      - "9000:80"
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media/
    depends_on:
      - backend
      - frontend
    restart: always